name: Otis Gallagher
favicon: null
layout_spectrum: 0.4780690409243107
typography_spectrum: 0.7511974875815213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3239217475056648
  lightness: 0.3442782836500555
  saturation: 0.10645114700309932
  rhythmicContrast: 0.6832434991374612
purpose: []
